Update control

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -1,12 +1,22 @@
 #!/bin/bash
 
 source $OPENSHIFT_CARTRIDGE_SDK_BASH
+source "${OPENSHIFT_MYSQL_DIR}/lib/mysql_context"
 
-export STOPTIMEOUT=10
+export OPENSHIFT_MYSQL_VERSION=$(mysql_version)
+
+start_timeout=45
+stop_timeout=30
+if [[ "${OPENSHIFT_MYSQL_START_TIMEOUT:-}" =~ ^[0-9]+$ ]] ; then
+    start_timeout="${OPENSHIFT_MYSQL_START_TIMEOUT}"
+fi
+if [[ "${OPENSHIFT_MYSQL_STOP_TIMEOUT:-}" =~ ^[0-9]+$ ]] ; then
+    stop_timeout="${OPENSHIFT_MYSQL_STOP_TIMEOUT}"
+fi
 
 # Run mysql commands
 function run_sql {
-  echo "$@" | /usr/bin/mysql -h $OPENSHIFT_MYSQL_DB_HOST -P $OPENSHIFT_MYSQL_DB_PORT -u $OPENSHIFT_MYSQL_DB_USERNAME --password="$OPENSHIFT_MYSQL_DB_PASSWORD" --skip-column-names
+  echo "$@" | mysql_context "/usr/bin/mysql -h $OPENSHIFT_MYSQL_DB_HOST -P $OPENSHIFT_MYSQL_DB_PORT -u $OPENSHIFT_MYSQL_DB_USERNAME --password='$OPENSHIFT_MYSQL_DB_PASSWORD' --skip-column-names"
 }
 
 function is_running {
@@ -30,8 +40,10 @@ function is_running {
 # Start mysqld and block until it comes up.
 function start {
   if ! is_running; then
-    echo "Starting MySQL cartridge"
-    /usr/bin/mysqld_safe --defaults-file=$OPENSHIFT_MYSQL_DIR/conf/my.cnf > /dev/null 2>&1 &    
+    echo "Starting MySQL ${OPENSHIFT_MYSQL_VERSION} cartridge"
+    rm -f $OPENSHIFT_LOG_DIR/mysql*.log
+    oo-erb ${OPENSHIFT_MYSQL_DIR}conf/my.cnf.erb.hidden > ${OPENSHIFT_MYSQL_DIR}conf/my.cnf
+    mysql_context "/usr/bin/mysqld_safe --defaults-file=$OPENSHIFT_MYSQL_DIR/conf/my.cnf --log-error=$OPENSHIFT_MYSQL_DIR/stdout.err |& /usr/bin/logshifter -tag mysql" &
     wait_for_mysqld_availability
   else
     echo "MySQL already running" 1>&2
@@ -41,7 +53,7 @@ function start {
 function wait_for_mysqld_availability {
   test_select=${1:-false}
 
-  for i in {1..30}; do
+  for (( i=1 ; i<=$start_timeout ; i++ )) ; do
     if is_running; then
       if $test_select; then
         run_sql 'select 1' 2> /dev/null && return 0
@@ -53,7 +65,12 @@ function wait_for_mysqld_availability {
     sleep 1
   done
 
-  return 1
+  # Send error logs to console, otherwise the logs file will be erased
+  # when MySQL server fail to start.
+  #
+  echo "MySQL server failed to start:"
+  cat $OPENSHIFT_LOG_DIR/mysql.log
+  exit 1
 }
 
 function stop {
@@ -61,17 +78,17 @@ function stop {
     pidfile=$OPENSHIFT_MYSQL_DIR/pid/mysql.pid
 
     if [ -f $pidfile ]; then
-      echo "Stopping MySQL cartridge"
+      echo "Stopping MySQL ${OPENSHIFT_MYSQL_VERSION} cartridge"
       pid=$( /bin/cat $pidfile )
       /bin/kill $pid
       ret=$?
       if [ $ret -eq 0 ]; then
-        TIMEOUT="$STOPTIMEOUT"
-        while [ $TIMEOUT -gt 0 ] && [ -f "$pidfile" ]
+        TIMEOUT="${stop_timeout}"
+        while [[ "${TIMEOUT}" > 0 && -f "${pidfile}" ]]
         do
-          /bin/kill -0 "$pid" >/dev/null 2>&1 || break
+          /bin/kill -0 "${pid}" >/dev/null 2>&1 || break
           sleep 1
-          let TIMEOUT=${TIMEOUT}-1
+          (( TIMEOUT-=1 ))
         done
       fi
     else
@@ -86,9 +103,9 @@ function stop {
 
 function status {
   if is_running; then
-    client_result "MySQL is running" 
+    client_result "MySQL is running"
   else
-    client_result "MySQL is stopped" 
+    client_result "MySQL is stopped"
   fi
 
   exit 0
@@ -109,12 +126,17 @@ function pre_snapshot {
   local db_port=$OPENSHIFT_MYSQL_DB_PORT
 
   {
-    /usr/bin/mysqldump --extended-insert --quick -h $db_host -P $db_port -u $OPENSHIFT_MYSQL_DB_USERNAME --password="$OPENSHIFT_MYSQL_DB_PASSWORD" --all-databases --events --triggers --routines --add-drop-table | /bin/gzip > $dump_file
+    mysql_context "/usr/bin/mysqldump --extended-insert --quick -h $db_host -P $db_port -u $OPENSHIFT_MYSQL_DB_USERNAME --password='$OPENSHIFT_MYSQL_DB_PASSWORD' --all-databases --events --triggers --routines --add-drop-table" | /bin/gzip > $dump_file
   } ||
   {
     warning "Couldn't not dump mysql! Continuing anyway"
     /bin/rm -rf $OPENSHIFT_DATA_DIR/mysql_dump_snapshot.gz
   }
+
+  if ! [ -s $OPENSHIFT_DATA_DIR/mysql_dump_snapshot.gz ]; then
+    warning "Insufficient disk space to dump mysql! Continuing anyway"
+    /bin/rm -rf $OPENSHIFT_DATA_DIR/mysql_dump_snapshot.gz
+  fi
 
   stop
 }
@@ -131,6 +153,10 @@ function post_restore {
   # Ensure a snapshot file exists
   if [ -f $OPENSHIFT_DATA_DIR/mysql_dump_snapshot.gz ]; then
     start
+
+    # The following call is necessary due to race conditions that can arise if mysql
+    # is recovering from a force-stop
+    wait_for_mysqld_availability true
 
     # Restore stashed variables and get current variables
     OLD_IP=$(< $OPENSHIFT_DATA_DIR/mysql_db_host)
@@ -163,14 +189,14 @@ function post_restore {
         echo "SET UNIQUE_CHECKS=1;"
         echo "SET AUTOCOMMIT=1;"
         echo "COMMIT;"
-      ) | /usr/bin/mysql -h $OPENSHIFT_MYSQL_DB_HOST -P $OPENSHIFT_MYSQL_DB_PORT -u $OPENSHIFT_MYSQL_DB_USERNAME --password="$OPENSHIFT_MYSQL_DB_PASSWORD" --skip-column-names
+      ) | mysql_context "/usr/bin/mysql -h $OPENSHIFT_MYSQL_DB_HOST -P $OPENSHIFT_MYSQL_DB_PORT -u $OPENSHIFT_MYSQL_DB_USERNAME --password='$OPENSHIFT_MYSQL_DB_PASSWORD' --skip-column-names"
     } || error "Could not import MySQL Database" 187
 
 
     # Grant permissions to the current user
     run_sql "
     GRANT ALL ON *.* TO '$NEW_USER'@'$NEW_IP' IDENTIFIED BY '$OPENSHIFT_MYSQL_DB_PASSWORD' WITH GRANT OPTION;
-    GRANT ALL ON *.* TO '$NEW_USER'@'localhost' IDENTIFIED BY '$OPENSHIFT_MYSQL_DB_PASSWORD' WITH GRANT OPTION;
+    GRANT ALL ON *.* TO '$NEW_USER'@'%' IDENTIFIED BY '$OPENSHIFT_MYSQL_DB_PASSWORD' WITH GRANT OPTION;
     " || error "Could not grant permissions for MySQL database" 187
 
     # Only run the following if the username is different
@@ -197,8 +223,8 @@ function post_restore {
       # This approach provides relational consistency and will work with tables, views, triggers, etc
       # TODO: This may not work if the user created another database that has references to this database
       {
-        /usr/bin/mysqldump -h $NEW_IP -P $OPENSHIFT_MYSQL_DB_PORT -u $NEW_USER --password="$OPENSHIFT_MYSQL_DB_PASSWORD" $OLD_NAME | \
-          mysql -h $NEW_IP -P $OPENSHIFT_MYSQL_DB_PORT -u $NEW_USER --password="$OPENSHIFT_MYSQL_DB_PASSWORD" $NEW_NAME
+        mysql_context "/usr/bin/mysqldump -h $NEW_IP -P $OPENSHIFT_MYSQL_DB_PORT -u $NEW_USER --password='$OPENSHIFT_MYSQL_DB_PASSWORD' $OLD_NAME" | \
+          mysql_context "/usr/bin/mysql -h $NEW_IP -P $OPENSHIFT_MYSQL_DB_PORT -u $NEW_USER --password='$OPENSHIFT_MYSQL_DB_PASSWORD' $NEW_NAME"
       } || error "Could not rename database" 187
 
       # Drop the old database now that the data has been preserved
@@ -206,6 +232,7 @@ function post_restore {
     fi
 
     cleanup_dump
+    stop
   else
     echo "MySQL restore attempted but no dump found!" 1>&2
     echo "$OPENSHIFT_DATA_DIR/mysql_dump_snapshot.gz does not exist" 1>&2
@@ -217,6 +244,13 @@ function cleanup_dump {
   rm -f $OPENSHIFT_DATA_DIR/mysql_db_host
   rm -f $OPENSHIFT_DATA_DIR/mysql_db_username
   rm -f $OPENSHIFT_DATA_DIR/mysql_db_dbname
+}
+
+# Clean up any log files
+function tidy() {
+  client_message "Deleting mysql logs from $OPENSHIFT_LOG_DIR"
+  shopt -s dotglob
+  rm -rf $OPENSHIFT_LOG_DIR/mysql.log*
 }
 
 case "$1" in
@@ -245,4 +279,5 @@ case "$1" in
   post-restore)
     post_restore
   ;;
+  tidy)          tidy ;;
 esac
